### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by jason-lange** [abehmiel/timescreen#1]
Hi, thanks for posting this. The whole process works for me up until I run tweetshot_driver. 
I installed pandas, node.js and phantom.js as per the readme. That is, I installed pandas via pip3, I used the windows installer for nodejs and, once nodejs was installed, I ran  npm install -g phantomjs in the command line. One thing not specified in the readme is how to use the tweetshot.js code. I created a .js file in notepad using the raw code for tweetshot.js, called is tweetshot.js and parked it in the same directory holding all the other files used in the process.
I run tweetshot_driver in Jupyter. The code breaks when i get to the for loop:
 for item in zip(urls, filepath):
    if not Path(item[1]).is_file():
        subprocess.call(["phantomjs", "tweetshot.js", item[0], item[1]])

At that point I get a FieleNotFoundError. The screenshot shows all the details. I've never used subprocess, nodejs or phantomjs. I saw development for phantomjs has been suspended. Might you have any ideas on why this isn't working?
Thanks!
Jason

![image](https://user-images.githubusercontent.com/10469285/50565530-cb627f80-0cfd-11e9-9f89-24124b1703b4.png)

**Comment by abehmiel** [comment]
This code hasn't been tested on Windows, and it looks like you're using it, is that right?

You will probably have to locate and copy/move the phantomjs executable file to the working directory path, or create a symbolic link in the current path to phantomjs, or create an environment variable that points to the location of phantomjs. Although you're right that phantomjs isn't under active development, it should still be usable. Where phantomjs actually is depends on whether you got it from node or downloaded it as a standalone package.

Let me know if that fixes the issue. I haven't done much with this code for over a year.

**Comment by jason-lange** [comment]
Thanks! I copied the phantomjs executable file to the working directory path and it is now pulling down screenshots. So this appears to be working just fine on my Windows 10. Thanks again!

**Comment by abehmiel** [comment]
Cool! glad to see that this is working. I'll add a note in the readme for windows machines. Can we close?

**Comment by jason-lange** [comment]
Definitely. Thanks again.
